# Generated by Django 6.0.1 on 2026-01-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dishes/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(max_length=750, verbose_name='Описание')),
                ('quote', models.CharField(max_length=100, verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('image', models.ImageField(upload_to='dish_ingredients/')),
            ],
            options={
                'verbose_name': 'Ингредиент Блюда',
                'verbose_name_plural': 'Ингредиенты Блюда',
            },
        ),
        migrations.CreateModel(
            name='DishIngredientGramm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramm', models.PositiveSmallIntegerField(help_text='Граммовка на 300 грамм блюдо', verbose_name='Грамм')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish', verbose_name='Блюдо')),
                ('dish_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishingredient', verbose_name='Ингредиент Блюда')),
            ],
            options={
                'verbose_name': 'Ингредиент Блюда Грамм',
                'verbose_name_plural': 'Ингредиенты Блюда Граммы',
                'unique_together': {('dish', 'dish_ingredient')},
            },
        ),
    ]
