# Generated by Django 6.0.1 on 2026-01-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishingredient',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
