# Generated by Django 6.0.1 on 2026-02-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dishingredient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredientgramm',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_gramms', to='dishes.dish', verbose_name='Блюдо'),
        ),
    ]
