# Generated by Django 6.0.1 on 2026-02-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_favoriteitems_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitems',
            name='favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites_items', to='dishes.favorite', verbose_name='Избранное'),
            preserve_default=False,
        ),
    ]
